server:
  port: 8080

spring:
  application:
    name: genericstructure
  datasource:
    url: jdbc:postgresql://localhost:5432/generic_structure_db
    username: generic_structure_user
    password: generic_structure_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

